name: Dependencies
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/dependencies.yml
  push:
    branches:
      - main
    paths:
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/dependencies.yml

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-dependencies:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@871e75bd8ff92b14f2a3fcbf6d156970dce9e218 # just
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
      - uses: taiki-e/install-action@0abfcd587b70a713fdaa7fb502c885e2112acb15 # v2
        with:
          tool: cargo-machete
      - uses: taiki-e/install-action@0abfcd587b70a713fdaa7fb502c885e2112acb15 # v2
        with:
          tool: cargo-audit

      - uses: taiki-e/install-action@0abfcd587b70a713fdaa7fb502c885e2112acb15 # v2
        with:
          tool: cargo-deny
      - run: just dep-check
