name: Build release binaries

on:
  push:
    branches:
      - main
    paths:
      - "**/assets/**"
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/release.yml

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            features: ""
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            features: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            features: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            features: ""
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            features: ""

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.platform.target }}
      - uses: taiki-e/install-action@just
      - if: matrix.platform.os == 'ubuntu-latest' || matrix.platform.os == 'ubuntu-24.04-arm'
        run: just install-debian-deps
      - if: matrix.platform.features != ''
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --features ${{ matrix.platform.features }}
      - if: matrix.platform.features == ''
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release
      - uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: infinigen
          changes-file: ""
          target: ${{ matrix.platform.target }}
